### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'seed'

### ISSUE THREAD

**Issue by zkytony** [webermarcolivier/statannot#58]
When I tried to use `add_state_annotation()` to a barplot, I get the following error:
```
Traceback (most recent call last):
  File "plotting.py", line 63, in result_plot
    add_stat_annotation(ax, plot="barplot", data=df,
  File "/home/myhome/pyenv/py37/lib/python3.7/site-packages/statannot/statannot.py", line 442, in add_stat_annotation
    errcolor=".26", errwidth=None, capsize=None, dodge=True)
TypeError: __init__() missing 1 required positional argument: 'seed'
```
I am using seaborn 0.11.0. I checked [seaborn's source code](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L1579) and indeed there is a required `seed` argument. I think this is a simple bug to be fixed. Also, it would be nice to have some barplot examples in the Jupyter Notebook, so that the barplot annotation functionality is tested:)

**Comment by ShawnGao911101** [comment]
Hi @zkytony , 

Just met the same problem. Have you sort it out? 

Cheers,
Shang

**Comment by zkytony** [comment]
I forked and fixed this in a commit https://github.com/zkytony/statannot/commit/504876162d4a1ba5cd1ae734ad6dbc6ec30dd343

**Comment by ShawnGao911101** [comment]
Many thanks mate, problem solved! @zkytony

**Comment by kpj** [comment]
See also https://github.com/webermarcolivier/statannot/issues/48.
